### ISSUE TITLE
homogenize profile output

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#117]
after some discussion it was decided, to make the content of the profiles, NR_profiles_ and OC_profiles files consistent. meaning same variable having same names. This means the near-range backscatter and far-range backscatter have the same variable name, but the filename were it is stored should be different as well as the meta data.

**Comment by ulysses78** [comment]
That is the way I also would do it. Great!

**Comment by ulysses78** [comment]
That means, that e.g.:
'NR_attenuated_backscatter_355nm' ---> 'attenuated_backscatter_355nm'

One question arrises at this point:
how to name the long_names of the variables?
Can we leave it as it is: 'near-field attenuated backscatter at 355 nm'?
Or do we have to change it to 'attenuated backscatter at 355 nm'?
In my opinion we can leave it as it is, because this is just an attribute, not a whole variable.
@HolgerPollyNet ... what do you think?

**Comment by ulysses78** [comment]
This affects the following files:
- pollySaveNRAttnBeta.m
- pollySaveNRProfiles.m
- pollySaveOCAttnBeta.m
- pollySaveOCProfiles.m

**Comment by HolgerPollyNet** [comment]
I think, we can leave it as the long-name is a more proper description and it would be give the chance for distinguishing.....
