### ISSUE TITLE
Raman bsc near-range height-shifted

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#160]
https://polly.tropos.de/datavis/location/35/25/?dates=[2019-12-02T00:00:00,2019-12-03T00:00:00]

![grafik](https://user-images.githubusercontent.com/55800803/172379200-d5732bff-4653-48da-945b-bfcd9d3729db.png)

Any ideas where to search? Test case 2019-12-02 arielle, config: arielle_config_mosaic.

**Comment by HolgerPollyNet** [comment]
currently running without dt correction - just for checking

**Comment by ZPYin** [comment]
It was caused by wrong indexing of far-range Raman channel for near-range Raman retrieval. I have fixed that in a new commit and make it updated in the server. 

You can check the re-processed results via the link below

https://polly.tropos.de/datavis/location/35/25/?dates=%5B2019-12-02T00:00:00,2019-12-03T00:00:00%5D


I would close this issue at the moment. If you have new comments in terms of this issue, feel free to re-open it.

**Comment by HolgerPollyNet** [comment]
Great! Many thanks!

**Comment by HolgerPollyNet** [comment]
I have one more comment: Do you have any clue why the near-range raman bsc can be comnpletely negatoive between 0.5 and 3 km, while the ref height is between 2.5. and 3 km? In my opinion this should not be possible: 
![grafik](https://user-images.githubusercontent.com/55800803/172582017-c90f53f5-5ad8-46b6-aed5-f366b9d475f7.png)

@ZPYin @griesche

**Comment by HolgerPollyNet** [comment]
sorry, my mistake
