### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#29]
For some plots the caption legend etc is not well behaving (overlaying, too big, too large). Check each output and modify.

**Comment by ZPYin** [comment]
Since there are quite a lot of figures, I would recommend to collect here with the figures that need to be improved. And it's better to explain which part needs to be improved. 

Below is an example:

![image](https://user-images.githubusercontent.com/7610928/82003800-d79d7180-9693-11ea-8698-7127c2078fca.png)

**Comment by HolgerPollyNet** [comment]
![grafik](https://user-images.githubusercontent.com/55800803/82050361-4f7d9300-96b8-11ea-8998-820695197eaf.png)

**Comment by ZPYin** [comment]
![image](https://user-images.githubusercontent.com/7610928/82108579-e94d4a80-9761-11ea-8d60-02733363fb11.png)

**Comment by ZPYin** [comment]
![image](https://user-images.githubusercontent.com/7610928/82108642-7a242600-9762-11ea-8434-a5f02130e7c8.png)

**Comment by ZPYin** [comment]
![image](https://user-images.githubusercontent.com/7610928/82108694-d9823600-9762-11ea-83d0-8ba85f74024c.png)

**Comment by HolgerPollyNet** [comment]
Ey, maybe I still need some time more ;-)

**Comment by ZPYin** [comment]
The figure issues raised above have been fixed in latest commits. If you find new issues, you can re-open this topic. 😃
