### ISSUE TITLE
Process historic data is not working anymore

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#85]
./pollynet_process_history_data.sh -s 20190915 -e 20190916 -p pollyxt_tjk -f [data folder]/pollyxt_tjk -c pollynet_processing_chain_config_rsd2_temp.json

Undefined function 'polly_parsetime' for input arguments of type 'char'.

Error in convert_temp_2_laserlogbook (line 66)
        measTime = polly_parsetime(pollyDataFile, pollyDataFileFormat);

Error in write_daily_to_filelist (line 86)
convert_temp_2_laserlogbook(config.fileinfo_new, pollyList, pollyTempFolder);

Error in pollynet_process_history_data (line 64)
    write_daily_to_filelist(pollyType, saveFolder, pollynetConfigFile, ...

>> Finish

**Comment by ZPYin** [comment]
This error was caused by the un-loaded search path for `./lib/polly_general_func_lib`,  where the function `polly_parsetime` located. To resolve this error, I have modified the code to load all sub-directories under `./lib`, in `pollynet_process_history_data`.

Have pushed it to rsd2. Now you can continue your un-processed work.
